language: node_js
dist: xenial
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    on_success: never
    on_failure: always
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
before_install:
- npm prune
install:
- npm i
- pip install -r requirements.txt --user
before_script:
- npx lint
script:
- npx test --silent
- "./scripts/pep8check.sh"
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    && git fetch --tags
    && npx travis-deploy-once "npx semantic-release" ; fi
