language: node_js
dist: xenial
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    on_success: never
    on_failure: always
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
before_install:
- npm prune
install:
- npm i
before_script:
- npm run build
- npm run lint
script:
- npm run test
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    npx travis-deploy-once "npx semantic-release" ; fi
