language: node_js
dist: focal
notifications:
  email:
    recipients:
      - middleware@hexonet.net
    on_success: never
    on_failure: always
node_js:
  - "12"
  - "11"
  - "10"
before_install:
  - npm prune
install:
  - travis_retry npm i
  - travis_retry pip install -r requirements.txt --user
before_script:
  - npm run lint
script:
  - npm run test --silent >/dev/null
  - "./scripts/pep8check.sh"
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npx semantic-release
