onlyBuiltDependencies:
  - esbuild

overrides:
  diff@>=6.0.0 <8.0.3: '>=8.0.3'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
  minimatch@>=9.0.0 <9.0.7: '>=9.0.7'
  serialize-javascript@<=7.0.2: '>=7.0.3'
