name: Dependabot auto-merge
on: 
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    permissions:
      contents: read

  dependabot:
    name: Auto-merge Dependabot PR
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    permissions:
      contents: write
      pull-requests: write
    needs: tests
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        # (fixes, features but not major upgrades!)
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'}}
        run: gh pr merge --auto -d -r "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.RTLDEV_MW_CI_TOKEN}}
