name: PR
"on":
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  quality:
    uses: ./.github/workflows/quality.yml

  tests:
    uses: centralnicgroup-opensource/rtldev-middleware-shareable-workflows/.github/workflows/idna-uts46-test.yml@main
    secrets: inherit
    with:
      pnpm-version: ""

  completed:
    name: "PR: completed"
    needs: [quality, tests]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check results
        run: |
          if echo '${{ join(needs.*.result, ' ') }}' | tr ' ' '\n' | grep -qvw success; then
            echo "One or more PR checks failed: ${{ join(needs.*.result, ' ') }}"
            exit 1
          fi
